openapi: 3.0.0
info:
  title: FetchMedia API - Fetch
  description: This is the Fetch endpoint for the FetchMedia API.
  version: v1
servers:
  - url: https://api.fetchmedia.io/v1
    description: Production server
paths:
  /fetch:
    post:
      summary: Create a fetch
      description: Creates a new fetch from a URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: url
                  description: The URL to fetch.
                  example: "https://www.youtube.com/watch?v=93npkPcQIzA"
                # quality:
                #   type: string
                #   description: The quality of the video to fetch.
                #   example: "1080p"
                webhook:
                  type: string
                  format: url
                  description: The URL to send a webhook to when the fetch is complete.
                  example: "https://example.com/webhook"
      responses:
        '201':
          description: Fetch created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchId'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /fetch/metadata:
    get:
      summary: Get video metadata
      description: Retrieves metadata for a video from a URL.
      parameters:
        - name: url
          in: query
          required: true
          schema:
            type: string
            format: url
            description: The URL to fetch metadata for.
            example: "https://www.youtube.com/watch?v=93npkPcQIzA"
      responses:
        '200':
          description: Video metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
    post:
      summary: Get video metadata
      description: Retrieves metadata for a video from a URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: url
                  description: The URL to fetch metadata for.
                  example: "https://www.youtube.com/watch?v=93npkPcQIzA"
      responses:
        '200':
          description: Video metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
  /fetch/{id}:
    get:
      summary: Get a fetch
      description: Retrieves a fetch by its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: The ID of the fetch to retrieve.
            example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: A fetch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fetch'
  /fetch/{id}/{filename}:
    get:
      summary: Download a fetched file
      description: Downloads a file that has been fetched.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: The ID of the fetch to retrieve.
            example: "123e4567-e89b-12d3-a456-426614174000"
        - name: filename
          in: path
          required: true
          schema:
            type: string
            description: The filename of the file to download.
            example: "output.mp4"
      responses:
        '302':
          description: Redirect to the file
          headers:
            Location:
              schema:
                type: string
                format: url
                description: Directed to an expiring URL to download the file.

components:
  schemas:
    FetchId:
      type: object
      properties:
        fetch_id:
          type: string
          format: uuid
          description: The ID of the fetch.
          example: "123e4567-e89b-12d3-a456-426614174000"
    Fetch:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The ID of the fetch.
          example: "123e4567-e89b-12d3-a456-426614174000"
        url:
          type: string
          format: url
          description: The URL that was fetched.
          example: "https://www.youtube.com/watch?v=93npkPcQIzA"
        status:
          type: string
          description: The status of the fetch.
          example: "running"
        download_url:
          type: string
          format: url
          description: The URL to download the fetched file.
          example: "https://api.fetchmedia.io/v1/fetch/123e4567-e89b-12d3-a456-426614174000/output.mp4"
        error:
          type: string
          description: The error message if the fetch failed.
          example: "An error occurred while fetching the file."
    Metadata:
      type: object
      properties:
        title:
          type: string
          description: The title of the video.
          example: "Video Title"
        description:
          type: string
          description: The description of the video.
          example: "Video Description"
        thumbnail:
          type: string
          format: url
          description: The thumbnail of the video.
          example: "https://example.com/thumbnail.jpg"
        duration:
          type: number
          description: The duration of the video.
          example: 123.45
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
security:
  - ApiKeyAuth: []
